In [4]:

# 1. Import the numpy package under the name np
import numpy as np

In [5]:

# 2. Print the numpy version and the configuration
np.show_config()


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/User/anaconda3/Library/include
    lib directory: C:/Users/User/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x8

In [6]:

# 3. Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:

# 4. How to find the memory size of any array
array = np.zeros((10, 10))
print(array.nbytes)


800


In [8]:
# 6. Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros(10)
vector[4] = 1
print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:

# 7. Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:

# 8. Reverse a vector (first element becomes last)
vector = np.arange(10)
reversed_vector = vector[::-1]
print(reversed_vector)


[9 8 7 6 5 4 3 2 1 0]


In [11]:

# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:

# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)[0]
print(indices)


[0 1 4]


In [13]:

# 11. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:

# 12. Create a 3x3x3 array with random values
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.22588124 0.7470948  0.29969695]
  [0.193184   0.88804444 0.80688879]
  [0.93924053 0.93334072 0.45193276]]

 [[0.48103551 0.58806617 0.45925621]
  [0.31364791 0.49186559 0.05225069]
  [0.98952226 0.52607063 0.60057153]]

 [[0.38423885 0.92076358 0.32932361]
  [0.92718077 0.09286772 0.5323376 ]
  [0.35842774 0.19940969 0.96983936]]]
